import { useEffect, useMemo, useState } from 'react';
import { catalogs } from './catalogs';
import { addItems, answer, bandFor, beginEdgeActivity, itemConfidence, itemOrder, listConfidence, newList, ready, refineItem, refineList, stopActivity } from './sort';
import { loadLists, removeList, saveList } from './storage';
import type { Answer, CatalogManifest, SortList } from './types';
type View = 'library'|'create'|'sort'|'result';
const base = import.meta.env.BASE_URL; const item = (list: SortList, id: string) => list.items.find(x => x.id === id)!; const label = (n:number) => n >= 85 ? 'High' : n >= 70 ? 'Placed' : 'Developing';
async function preset(id:string, fallback:string[]) { try { const manifest = await fetch(`${base}catalogs/${id}/manifest.json`).then(r => r.ok ? r.json() as Promise<CatalogManifest> : Promise.reject()); const chunk = await fetch(`${base}catalogs/${id}/${manifest.chunks[0].file}`).then(r => r.json() as Promise<{items:Array<{label:string}>}>); return { labels: chunk.items.map(x=>x.label), catalog: { id, nextChunk: 1, nextItem: 0, totalChunks: manifest.chunks.length, source: 'static' as const } }; } catch { return { labels: fallback, catalog: { id, nextChunk: 1, nextItem: 0, totalChunks: 1, source: 'starter' as const } }; } }
function Preview({list}:{list:SortList}) { const order = itemOrder(list); if (!order.length) return null; const focus = list.ranking.current?.leftId ?? order[0]; const at = Math.max(0, order.indexOf(focus)); const start = Math.max(0, Math.min(at-4, order.length-9)); return <aside className="provisional"><h2>Provisional full list</h2>{start>0&&<span className="ellipsis">···</span>}<ol>{order.slice(start,start+9).map((id,i)=><li className={id===focus?'focus':''} key={id}><span>{start+i+1}</span><strong>{item(list,id).label}</strong><small>{bandFor(list,id)}</small></li>)}</ol>{start+9<order.length&&<span className="ellipsis">···</span>}</aside>; }
export default function App(){
 const [lists,setLists]=useState<SortList[]>([]),[active,setActive]=useState<SortList>(),[view,setView]=useState<View>('library'),[name,setName]=useState('My ranking'),[paste,setPaste]=useState(''),[presetId,setPresetId]=useState(''),[addText,setAddText]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{loadLists().then(x=>setLists(x.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))));},[]);
 const persist=(list:SortList)=>{setActive(list);setLists(old=>[list,...old.filter(x=>x.id!==list.id)].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));saveList(list);};
 const open=(list:SortList)=>{persist(ready(list));setView('result');};
 const create=async()=>{setLoading(true);const selected=catalogs.find(c=>c.id===presetId);const loaded=selected?await preset(selected.id,selected.items):{labels:paste.split(/\r?\n/),catalog:undefined};persist(ready(newList(name.trim()||selected?.name||'Untitled ranking',loaded.labels,loaded.catalog)));setView('sort');setLoading(false);};
 const trickle=async(list:SortList)=>{const resumeWithoutReplacement=()=>persist(ready({...list,ranking:{...list.ranking,trickleDue:false,replacementDue:false}}));if(!list.catalog||list.catalog.source!=='static'||list.catalog.nextChunk>=(list.catalog.totalChunks??0)){resumeWithoutReplacement();return;} try{const manifest=await fetch(`${base}catalogs/${list.catalog.id}/manifest.json`).then(r=>r.json() as Promise<CatalogManifest>);const chunk=await fetch(`${base}catalogs/${list.catalog.id}/${manifest.chunks[list.catalog.nextChunk].file}`).then(r=>r.json() as Promise<{items:Array<{label:string}>}>);const title=chunk.items[list.catalog.nextItem]?.label;if(!title){resumeWithoutReplacement();return;}const added=addItems(list,[title]);const atEnd=list.catalog.nextItem+1>=chunk.items.length;const carry=added.ranking.carry;const newcomer=added.items[added.items.length-1].id;const current=list.ranking.replacementDue&&carry?(carry.side==='right'?{leftId:newcomer,rightId:carry.itemId}:{leftId:carry.itemId,rightId:newcomer}):added.ranking.current;persist({...added,catalog:{...list.catalog,nextChunk:atEnd?list.catalog.nextChunk+1:list.catalog.nextChunk,nextItem:atEnd?0:list.catalog.nextItem+1},ranking:{...added.ranking,current,trickleDue:false,replacementDue:false}});}catch{resumeWithoutReplacement();}};
 const respond=(outcome:Answer)=>{if(!active)return;const next=answer(active,outcome);persist(next);if(next.ranking.trickleDue)void trickle(next);};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(view!=='sort'||!active||(e.target as HTMLElement)?.tagName==='TEXTAREA')return;const left=e.key==='ArrowLeft'||e.key.toLowerCase()==='a',right=e.key==='ArrowRight'||e.key.toLowerCase()==='d',tie=e.key.toLowerCase()==='w'||e.key==='ArrowUp'||e.key==='ArrowDown'||e.code==='Space';if(left||right||tie)e.preventDefault();if(left)respond(e.shiftKey?'unavailable-left':'left');if(right)respond(e.shiftKey?'unavailable-right':'right');if(tie)respond('tie');};addEventListener('keydown',key);return()=>removeEventListener('keydown',key);});
 const pair=active?.ranking.current?{left:item(active,active.ranking.current.leftId),right:item(active,active.ranking.current.rightId)}:undefined;const order=useMemo(()=>active?itemOrder(active):[],[active]);const confidence=active?listConfidence(active):0;const activity=active?.ranking.activity.kind??'normal';const activityName=activity==='refine-top'?'Refining Top 10 contenders':activity==='refine-bottom'?'Refining Bottom 10 contenders':activity==='refine-list'?'Refining broad placements':activity==='refine-item'?'Refining this item':'Discovering new items';const injectionText=active?.catalog?.source==='static'&&activity==='normal'?`New item in ${5-(active.ranking.normalAnswers%5)} normal comparisons`:undefined;
 return <main><header><button className="brand" onClick={()=>setView('library')}>Stackrank</button><span>Discovery-first personal rankings</span></header>
 {view==='library'&&<section className="panel"><div className="split"><div><h1>Your rankings</h1><p>Saved privately in this browser.</p></div><button className="primary" onClick={()=>{setName('My ranking');setPaste('');setPresetId('');setView('create');}}>New ranking</button></div>{lists.length?<div className="list">{lists.map(l=><article key={l.id}><div><strong>{l.name}</strong><small>{l.items.length-l.unrankedIds.length} items · {listConfidence(l)}% broad placement</small></div><div><button onClick={()=>open(l)}>Open</button><button className="danger" onClick={()=>{removeList(l.id);setLists(all=>all.filter(x=>x.id!==l.id));}}>Delete</button></div></article>)}</div>:<p className="empty">No saved rankings yet.</p>}</section>}
 {view==='create'&&<section className="panel"><button className="back" onClick={()=>setView('library')}>← Library</button><h1>Start a ranking</h1><label>Ranking name<input value={name} onChange={e=>setName(e.target.value)}/></label><h2>Choose a preset</h2><div className="cards">{catalogs.map(c=><button key={c.id} className={presetId===c.id?'card selected':'card'} onClick={()=>{setPresetId(c.id);setName(c.name);}}><strong>{c.name}</strong><small>{c.description}</small></button>)}</div><div className="or">or paste your own list</div><label>One item per line<textarea value={paste} onChange={e=>{setPaste(e.target.value);setPresetId('');}}/></label><button className="primary" disabled={loading||(!presetId&&!paste.trim())} onClick={create}>{loading?'Loading…':'Start sorting'}</button></section>}
 {view==='sort'&&active&&<><Preview list={active}/><section className="sort"><div className="progress"><button className="back" onClick={()=>setView('library')}>Save & library</button><button onClick={()=>setView('result')}>View list anytime</button><span>{activityName}{injectionText&&<> · {injectionText}</>}</span></div>{pair&&<><p className="prompt">Which do you prefer?</p><div className="comparison"><button className="choice" onClick={()=>respond('left')}><kbd>A / ←</kbd><strong>{pair.left.label}</strong><small>{active.ranking.ratings[pair.left.id].comparisons === 0 ? <span className="new-item">New item</span> : `${active.ranking.ratings[pair.left.id].comparisons} comparisons · ${itemConfidence(active,pair.left.id)}% placement confidence`}</small></button><button className="choice" onClick={()=>respond('right')}><kbd>D / →</kbd><strong>{pair.right.label}</strong><small>{active.ranking.ratings[pair.right.id].comparisons === 0 ? <span className="new-item">New item</span> : `${active.ranking.ratings[pair.right.id].comparisons} comparisons · ${itemConfidence(active,pair.right.id)}% placement confidence`}</small></button></div><div className="actions"><button onClick={()=>respond('tie')}><kbd>W / ↑ / ↓ / Space</kbd>No preference</button><button onClick={()=>respond('unavailable-left')}>Shift+A / ← Haven't had left</button><button onClick={()=>respond('unavailable-right')}>Shift+D / → Haven't had right</button>{activity!=='normal'&&<button onClick={()=>{persist(stopActivity(active));setView('result');}}>Leave activity</button>}</div></>}</section></>}
 {view==='result'&&active&&<section className="panel"><div className="split"><div><button className="back" onClick={()=>setView('library')}>← Library</button><h1>{active.name}</h1><p><strong>{confidence}% {label(confidence)}</strong> broad placement confidence. New preset items arrive every five normal comparisons.</p></div><div className="actions"><button className="primary" onClick={()=>{persist(ready(active));setView('sort');}}>Keep discovering</button><button onClick={()=>{persist(refineList(active));setView('sort');}}>Refine broad bands</button><button onClick={()=>{persist(beginEdgeActivity(active,'top'));setView('sort');}}>Refine Top 10</button><button onClick={()=>{persist(beginEdgeActivity(active,'bottom'));setView('sort');}}>Refine Bottom 10</button></div></div><label>Add custom items<textarea value={addText} onChange={e=>setAddText(e.target.value)}/></label><button onClick={()=>{if(addText.trim()){persist(addItems(active,addText.split(/\r?\n/)));setAddText('');setView('sort');}}}>Add & sort</button><ol className="results">{order.map((id,index)=>{const current=item(active,id),c=itemConfidence(active,id);return <li key={id}><span>{index+1}</span><div><strong>{current.label}</strong><small>{bandFor(active,id)} · {c}% {label(c)}</small></div><button onClick={()=>{persist(refineItem(active,id));setView('sort');}}>Refine this item</button></li>;})}</ol></section>}
 </main>;
}
